@extends('Layout.master')

<?php

$title = 'Product Report';

?>

@section('title')
{{ $title }}
@endsection

@section('content')

<style>
    /*
    #navbar, #sidebar{
        display: none;
    }
    */
    .widget-body .table{
        margin: 0px;
    }
    </style>

<div style="display:none;">

    A "Sales by Product" report provides a detailed breakdown of sales performance for individual products or product categories within a specified time period. Here's a more detailed description of what such a report typically includes:

    Product Information:

    Product Name/ID: Each product is listed along with its name or unique identifier (such as SKU or barcode).
    Description: A brief description of each product, which may include details like size, color, or other variants.
    Category/Department: Products may be grouped into categories or departments for easier analysis. This helps identify which product categories are driving sales.
    Sales Metrics:

    Quantity Sold: The total number of units of each product sold during the specified time period.
    Revenue: The total revenue generated by the sales of each product. This is calculated by multiplying the quantity sold by the selling price of each unit.
    Cost of Goods Sold (COGS): The direct cost associated with producing or purchasing the products sold. COGS is subtracted from revenue to calculate gross profit.
    Gross Profit: The difference between revenue and the cost of goods sold. It represents the profit generated from the sale of each product before deducting operating expenses.
    Profit Margin: The percentage of revenue that represents profit after deducting the cost of goods sold. It's calculated as (Gross Profit / Revenue) * 100.
    Performance Metrics:

    Average Selling Price: The average price at which each unit of the product was sold during the specified period. It's calculated as (Revenue / Quantity Sold).
    Units Sold per Transaction: The average number of units of each product included in a single transaction. This metric helps identify product bundling or cross-selling opportunities.
    Sales Growth: A comparison of sales performance for each product between the current period and a previous period (e.g., compared to the same period last year). It indicates whether sales are increasing or decreasing over time.
    Trends and Analysis:

    Graphical Representation: Visualizations such as charts or graphs may be included to illustrate sales trends for each product over time. This helps identify seasonal fluctuations, product popularity, or sales patterns.
    Top Sellers: A list of the best-selling products ranked by revenue or quantity sold. This highlights the products that contribute the most to overall sales.
    Customization Options:

    Time Period: The report can be generated for a specific date range, such as daily, weekly, monthly, quarterly, or annually.
    Filters: Users can apply filters to focus on specific products, categories, locations, or other relevant criteria.
    Export Options: The ability to export the report data in various formats (e.g., CSV, Excel) for further analysis or integration with other systems.
    Overall, a Sales by Product report provides valuable insights into the performance of individual products, helping businesses make data-driven decisions related to pricing, inventory management, marketing strategies, and product development.

</div>



<div class="page-content">

    <div class="page-header" style="min-height:40px;">
        <div class="" style="float: left;">
            <h1>{{ $title }}</h1>
        </div>
        {{-- <div class="" style="float: right;">
        <a href="{{ route('Settings.project.create') }}" class="btn btn-xs btn-light bigger"><i class="ace-icon fa fa-floppy-o"></i> Add Record </a>
    </div> --}}
</div>


<div class="row">
    <div class="col-xs-12 col-sm-12 widget-container-col" id="widget-container-col-1">
        <div class="widget-box" id="widget-box-1">
            <div class="widget-header widget-header-small">
                <h5 class="widget-title">Filters</h5>
                <div class="widget-toolbar">
                    <a href="#" data-action="collapse">
                        <i class="ace-icon fa fa-chevron-up"></i>
                    </a>
                </div>
            </div>

            <div class="widget-body">
                <!---------->
                <div class="widget-main">

                    <form name="filterForm">
                        <div class="row">
                            <div class="col-lg-3 col-sm-3">
                                <label>Product</label>
                                <select name="product_ids" id="product_ids" data-placeholder="Select Product" onchange="getResultsByProductId();" class="col-lg-12 select_chosen chosen-multi-select" >
                                <option value=""></option>
                                    @foreach($products as $product)
                                        <option value="{{ $product->id }}">{{ $product->name }}</option>
                                    @endforeach;
                                </select>
                            </div>
                            <div class="col-lg-3 col-sm-3">
                                <label>Date Range</label>
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-calendar bigger-110"></i></span>
                                    <div><input type="text" class="form-control" name="date_range" id="date_range" type="text" placeholder="Date To" placeholder="Date" autocomplete="off"></div>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
                <!----------------->
                <div class="widget-toolbox padding-8 clearfix">
                    <button class="btn btn-xs btn-success pull-right" onclick="refershDataTable();">
                        <span class="bigger-110">Search</span>
                        <i class="ace-icon fa fa-check icon-on-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>



<!------------------------------------------------------------------------------------------------------------------------------------->
<div class="row">
    <div class="col-xs-12 col-sm-12 widget-container-col" id="widget-container-col-1">
        <div class="widget-box" id="widget-box-1">
            <div class="widget-header widget-header-small">
                <h5 class="widget-title">Product Information</h5>
                <div class="widget-toolbar">
                    <a href="#" data-action="collapse">
                        <i class="ace-icon fa fa-chevron-up"></i>
                    </a>
                </div>
            </div>
            <div class="widget-body">
                <!---------->
                
                <div class="widget-main">
                    <table class="table table-striped table-bordered no-footer">
                        <tr class="odd" ><td class="even">Name : <b id="pro_name"></b> </td>  <td>Description : <b id="pro_desc"></b> </td></tr>
                    </table>
                    <table class="table table-striped table-bordered no-footer">
                        <tr class="odd" >
                            <td class="even">Cost Price (Rs) : <b id="pro_cost_price" > -- </b> </td> 
                            <td>Sale Price (Rs) : <b id="pro_sale_price" > -- </b> </td>
                        </tr>
                    </table>
                    <table class="table table-striped table-bordered no-footer">
                        <tr class="odd" >
                            <td>Total Purchase (Pair) : <b id="pro_total_purchase_qty"> --  </b> </td> <td> Total Purchase (Rs) : <b id="pro_total_purchase_price" > -- </b> </td> 
                        </tr>
                        <tr class="odd" >
                            <td>Total Sale (Pair) : <b id="pro_total_sale_qty" > --  </b> </td> <td> Total Sale (Rs) : <b id="pro_total_sale_price" > -- </b> </td> 
                        </tr>
                    </table>

                    <table class="table table-striped table-bordered no-footer">
                        <tr class="odd" >
                            <td colspan="3" ><b>Available in Shop</b></td> 
                        </tr>
                        <tr class="odd" > 
                            <td>Total Available (Pair) : <b id="pro_total_available_qty" > --  </b> </td> <td> Total Available (Rs) : <b id="pro_total_available_price" > -- </b> </td> 
                        </tr>
                    </table>

                </div>

                <!----------------->
                <div class="widget-toolbox padding-8 clearfix">
                    Shops
                </div>



                <div class="widget-main">
                    <table class="table table-striped table-bordered table-hover no-margin-bottom no-border-top no-footer">
                        <thead>
                            <tr>
                                <td>Shop</td> 
                                <td>Total Purchase (Pair) : </td> 
                                <td>Total Purchase (Rs) :</td> 
                                <td>Total Sale (Pair) : </td>
                                <td> Total Sale (Rs) :</td>
                            </tr>
                        </thead>
                        <tbody id="shop_table_body">
                            <tr>
                                <td colspan="5" >---</td> 
                            </tr>
                        </tbody>
                    </table>
                </div>

<!----------------------------      Purchase       --------------------------->
<div class="widget-toolbox padding-8 clearfix">
    Purchase
</div>
<div class="widget-main">
    <table id="product_purchase_table" class="table table-striped table-bordered table-hover no-margin-bottom no-border-top no-footer">
        
    </table>
</div>


                <!----------------------------      Orders       --------------------------->
<div class="widget-toolbox padding-8 clearfix">
    Orders
</div>
<div class="widget-main">
    <table id="order_table" class="table table-striped table-bordered table-hover no-margin-bottom no-border-top no-footer">
        
    </table>
</div>





            </div>
        </div>
    </div>
</div>
<!----------------------------------------------------------------------------------------------------------------------------------------------->




<div class="row ">
    <div class="col-12 col-lg-12" style="margin-top:20px;">

        <div class="card radius-10 border-top border-0 border-4 border-danger">


            <div class="card-body">

                @include('Layout.alerts')

                <div class="table-responsive">
                    <table class="table table-striped table-bordered yajratable" id="yajra-table" style="width:100%"></table>
                </div>
            </div>



        </div>
    </div>
</div>
<!--end row-->

</div>
@endsection
@section('script')
<script src="{{ asset('assets/css/rowGroup.dataTables.min.css')}}"></script>
<script src="{{ asset('assets/app-js/filters.js')}}?ver=<?= time() ?>"></script>
<script src="{{ asset('assets/js/dataTables.rowGroup.min.js')}}"></script>



<script>
    var saleTable;
    var purchaseTable;

    function date_range_cb_check() {
        if ($('#date_range_cb').is(':checked')) {
            console.log('i am checked');
        } else {
            $('input[name=date_range]').val('');
            console.log('i am un checked');
        }
    }


    function getResultsByProductId(){
        var productId = $('#product_ids').val();
        saleTable.ajax.reload();
        purchase_table.ajax.reload();

        $.ajax({
            dataType: 'json',
            type: 'get',
            url: "{{ route('report.product') }}?product_id="+productId,
            success: function(res) {
                console.log(res);

                var productDetail = res.product_detail;
                var productStat = res.product_stats;

                $('#pro_name').html(productDetail.name);
                $('#pro_cost_price').html(productDetail.cost_price);
                $('#pro_sale_price').html(productDetail.price);
                
                $('#pro_total_sale_qty').html(productStat.sale_count);
               // $('#pro_total_sale_price').html(productStat);

                $('#pro_total_purchase_qty').html(productStat.purchase_count);
               // $('#pro_total_purchase_qty').html(productStat);

                $('#pro_total_available_qty').html(productStat.available_count);
               // $('#pro_total_available_price').html(productStat);

                var html = '';
                $(res.product_stats_shops_wise).each(function(index, row){
                    html += '<tr><td>'+row.name+'</td><td>'+row.name+'</td><td>5800</td><td>15600</td><td>265878</td></tr>'; 
                });
                $('#shop_table_body').html(html);
                // <tr><td>ABC Store</td><td>458</td><td>5800</td><td>15600</td><td>265878</td></tr>
            }
        });
    }


    $(document).ready(function() {

        $('.select21').chosen({
            allow_single_deselect: true
        });





        // order_table
        function orderTable() {



    saleTable = $('#order_table').DataTable({
                    processing: true,
                    serverSide: true,
                  //   ajax: "{{ route('report.product_order_table') }}?group_by=issue_key",
                  ajax: {
                url: "{{ route('report.product_order_table') }}",
                type: 'GET',
                data: function (d) {
                    d.product_id = $('#product_ids').val()
                }
            },
                    columns: [{
                            data: 'id',
                            name: 'id',
                            title: 'ID.',
                            width:'5%'
                        },{
                            data: 'customer_name',
                            name: 'customer_name',
                            title: 'Customer',
                        },
                        {
                            data: 'this_product_unit_price',
                            name: 'this_product_unit_price',
                            title: 'Product Sale Price',
                        },
                        {
                            data: 'this_product_item_count',
                            name: 'this_product_item_count',
                            title: 'Product Count',
                        },
                        {
                            data: 'this_product_total_bill',
                            name: 'this_product_total_bill',
                            title: 'Product Bill',
                        },
                        {
                            data: 'item_count',
                            name: 'item_count',
                            title: 'Order Items',
                        
                        },{
                            data: 'total_offer_price',
                            name: 'total_offer_price',
                            title: 'Offer Amount',
                        
                        },{
                            data: 'total_price',
                            name: 'total_price',
                            title: 'Bill Price',
                        },{
                            data: 'total_discount',
                            name: 'total_discount',
                            title: 'Total Discount',
                        
                        },{
                            data: 'shop_name',
                            name: 'shop_name',
                            title: 'Shop',
                        
                        },{
                            data: 'order_time',
                            name: 'order_time',
                            title: 'Date N Time',
                        
                        },
                        {
                            data: 'action',
                            name: 'action',
                            title: 'Action'
                        }
                    ],
                    order: [[0, 'desc']]
                });
           
        }


        function purchaseTable(){
            // product_purchase_table

    purchase_table = $('#product_purchase_table').DataTable({
            // lengthMenu: [
            //         [1, 2, 3, -1],
            //         [1, 2, 3, 'All'],
            //     ],
            // "aLengthMenu": [[1,5,10, 25, 50, 100, -1], [1,5,10, 25, 50, 100, "All"]],
            // 					"iDisplayLength": -1,
            // dom: 'Bfrtip',
            // buttons: ['excel'],
            processing: true,
            serverSide: true,
          //   ajax: "{{ route('report.product_purchase_table') }}",
          ajax: {
                url: "{{ route('report.product_purchase_table') }}",
                type: 'GET',
                data: function (d) {
                    d.product_id = $('#product_ids').val()
                }
            },
            columns: [
                  {data: 'id', name: 'id', title : 'ID'},
                // {
                //     "data": "id",
                //     title: 'Sr.',
                //     render: function(data, type, row, meta) {
                //         return meta.row + meta.settings._iDisplayStart + 1;
                //     }
                // },
                {
                    data: 'info_no',
                    name: 'info_no',
                    title: 'Invoice & Challan & POI',
                    width: '20%'
                },
                {
                    data:'supplier',
                    name:'supplier',
                    title:'Supplier'
                },
          
                {
                    data:'delivery_amount',
                    name:'delivery_amount',
                    title:'Total Amount'
                },
                {
                    data: 'items_count',
                    name: 'items_count',
                    title: 'Product Count',
                    width: '10%'
                },
                {
                    data:'purchased_date_new',
                    name:'purchased_date_new',
                    title:'Purchase Date'
                },
                {
                    data:'create',
                    name:'create',
                    title:'Created at'
                },
                {
                    data: 'action',
                    name: 'action',
                    title: 'Action'
                }
            ],
            order: [[0, 'desc']]
        });
        }


       //  initDataTableRecord();
        orderTable();
        purchaseTable();
        $('.select_chosen').chosen();


    });
</script>
@endsection